FROM oven/bun:1.3.13 AS builder

WORKDIR /app

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

COPY . .
RUN bunx nx build backend --configuration=production

FROM node:25.9.0-bookworm AS runner

WORKDIR /app
ENV NODE_ENV=production
ENV PORT=4000

COPY --from=builder /app/dist/apps/backend ./
RUN npm install --omit=dev

EXPOSE 4000

CMD ["node", "main.js"]
