export const JOB_POSTING_SKILL_PRESETS = [
  'Python',
  'JavaScript',
  'TypeScript',
  'React',
  'Node.js',
  'SQL',
  'PostgreSQL',
  'MongoDB',
  'Java',
  'C++',
  'Machine Learning',
  'Data Analysis',
  'Excel',
  'Tableau',
  'Project Management',
  'Communication',
  'Leadership',
  'Marketing',
  'Sales',
  'Customer Service',
  'Figma',
  'UI/UX Design',
  'Docker',
  'AWS',
  'Git',
] as const;
