export const MAJOR_SKILLS_MAP: Record<string, string[]> = {
  'computer science':   ['Python', 'JavaScript', 'TypeScript', 'React', 'Node.js', 'SQL', 'Git', 'Docker', 'AWS', 'Java', 'C++', 'Algorithms', 'Data Structures'],
  'software':           ['Python', 'JavaScript', 'TypeScript', 'React', 'Node.js', 'Git', 'Docker', 'REST APIs', 'Agile', 'Testing', 'CI/CD'],
  'information technology': ['Networking', 'Cybersecurity', 'Linux', 'Cloud Computing', 'AWS', 'Azure', 'SQL', 'IT Support', 'Docker', 'Python'],
  'cybersecurity':      ['Network Security', 'Penetration Testing', 'Firewalls', 'Linux', 'Python', 'Cryptography', 'SIEM', 'Risk Assessment', 'Ethical Hacking'],
  'web':                ['HTML', 'CSS', 'JavaScript', 'React', 'TypeScript', 'Node.js', 'REST APIs', 'Figma', 'Git', 'Responsive Design'],
  'mobile':             ['React Native', 'Swift', 'Kotlin', 'Flutter', 'iOS', 'Android', 'Firebase', 'REST APIs', 'Git'],
  'artificial intelligence': ['Python', 'Machine Learning', 'Deep Learning', 'TensorFlow', 'PyTorch', 'NLP', 'Computer Vision', 'Pandas', 'NumPy', 'Statistics'],
  'machine learning':   ['Python', 'TensorFlow', 'PyTorch', 'Scikit-learn', 'Pandas', 'NumPy', 'Statistics', 'SQL', 'Data Visualisation', 'Deep Learning'],
  'data science':       ['Python', 'R', 'SQL', 'Machine Learning', 'Pandas', 'NumPy', 'Tableau', 'Power BI', 'Statistics', 'Data Visualisation', 'Excel'],
  'data analytics':     ['SQL', 'Excel', 'Tableau', 'Power BI', 'Python', 'R', 'Statistics', 'Data Visualisation', 'Google Analytics', 'ETL'],
  'data engineering':   ['Python', 'SQL', 'Apache Spark', 'Kafka', 'Airflow', 'AWS', 'Azure', 'ETL', 'PostgreSQL', 'MongoDB', 'Docker'],
  'database':           ['SQL', 'PostgreSQL', 'MySQL', 'MongoDB', 'Oracle', 'Database Design', 'Query Optimisation', 'ETL', 'Data Modelling'],
  'statistics':         ['R', 'Python', 'SPSS', 'Stata', 'Excel', 'Statistical Modelling', 'Hypothesis Testing', 'Data Visualisation', 'SAS'],
  'mathematics':        ['MATLAB', 'Python', 'R', 'Statistics', 'Linear Algebra', 'Calculus', 'Mathematical Modelling', 'Excel', 'LaTeX'],
  'business':           ['Project Management', 'Leadership', 'Communication', 'Microsoft Office', 'Excel', 'PowerPoint', 'Business Analysis', 'Strategic Planning', 'CRM'],
  'management':         ['Project Management', 'Leadership', 'Team Management', 'Budgeting', 'Strategic Planning', 'Communication', 'Problem Solving', 'CRM', 'Agile'],
  'entrepreneurship':   ['Business Development', 'Pitching', 'Financial Planning', 'Marketing', 'Leadership', 'Networking', 'Product Management', 'Strategic Planning'],
  'supply chain':       ['Logistics', 'SAP', 'Inventory Management', 'Procurement', 'Excel', 'Supply Chain Management', 'ERP', 'Data Analysis', 'Operations'],
  'operations':         ['Process Improvement', 'Lean', 'Six Sigma', 'ERP', 'SAP', 'Excel', 'Supply Chain', 'Project Management', 'Budgeting'],
  'project management': ['Agile', 'Scrum', 'JIRA', 'MS Project', 'Risk Management', 'Budgeting', 'Stakeholder Management', 'Leadership', 'Communication'],
  'accounting':         ['Excel', 'MYOB', 'Xero', 'QuickBooks', 'Financial Reporting', 'Tax', 'Auditing', 'Bookkeeping', 'Financial Analysis', 'SAP'],
  'finance':            ['Financial Analysis', 'Excel', 'Bloomberg', 'Financial Modelling', 'Valuation', 'Risk Management', 'Investment Analysis', 'Power BI', 'SQL'],
  'economics':          ['Econometrics', 'R', 'Stata', 'Excel', 'Financial Analysis', 'Policy Analysis', 'Data Analysis', 'Statistics', 'Research'],
  'actuarial':          ['Excel', 'R', 'Python', 'Statistics', 'Risk Modelling', 'SAS', 'Financial Maths', 'Actuarial Software', 'Data Analysis'],
  'banking':            ['Financial Analysis', 'Risk Management', 'Excel', 'Bloomberg', 'Credit Analysis', 'AML', 'Compliance', 'Financial Modelling'],
  'marketing':          ['Digital Marketing', 'SEO', 'SEM', 'Google Analytics', 'Social Media', 'Content Creation', 'Email Marketing', 'Adobe Creative Suite', 'HubSpot', 'Copywriting'],
  'digital marketing':  ['SEO', 'SEM', 'Google Ads', 'Facebook Ads', 'Google Analytics', 'Content Marketing', 'Email Marketing', 'HubSpot', 'Social Media Management'],
  'communication':      ['Copywriting', 'Public Relations', 'Media Relations', 'Social Media', 'Content Creation', 'Presentation', 'Journalism', 'Adobe Creative Suite'],
  'public relations':   ['Media Relations', 'Copywriting', 'Press Releases', 'Crisis Management', 'Social Media', 'Stakeholder Engagement', 'Event Management'],
  'journalism':         ['Writing', 'Research', 'Interviewing', 'Editing', 'Social Media', 'Video Production', 'Photography', 'CMS', 'Content Management'],
  'advertising':        ['Creative Strategy', 'Copywriting', 'Adobe Creative Suite', 'Social Media', 'Campaign Management', 'Market Research', 'Analytics'],
  'design':             ['Figma', 'Adobe Photoshop', 'Illustrator', 'InDesign', 'UI/UX Design', 'Wireframing', 'Prototyping', 'Typography', 'Branding'],
  'graphic design':     ['Adobe Photoshop', 'Illustrator', 'InDesign', 'Figma', 'Typography', 'Branding', 'Print Design', 'Motion Graphics', 'Canva'],
  'ux':                 ['Figma', 'User Research', 'Wireframing', 'Prototyping', 'Usability Testing', 'Information Architecture', 'Adobe XD', 'Design Thinking'],
  'ui':                 ['Figma', 'Adobe XD', 'HTML', 'CSS', 'JavaScript', 'Wireframing', 'Prototyping', 'Design Systems', 'Responsive Design'],
  'fashion':            ['Trend Forecasting', 'Garment Construction', 'Adobe Illustrator', 'Pattern Making', 'Textile Knowledge', 'Fashion Styling', 'Merchandising'],
  'architecture':       ['AutoCAD', 'Revit', 'SketchUp', '3ds Max', 'Rhino', 'Adobe Creative Suite', 'BIM', 'Building Codes', 'Project Management'],
  'engineering':        ['CAD', 'AutoCAD', 'Project Management', 'MATLAB', 'Python', 'Problem Solving', 'Technical Drawing', 'Quality Control', 'Safety Management'],
  'mechanical':         ['AutoCAD', 'SolidWorks', 'MATLAB', 'FEA', 'Thermodynamics', 'Manufacturing', 'CAD/CAM', 'Project Management', 'Quality Control'],
  'electrical':         ['Circuit Design', 'MATLAB', 'AutoCAD', 'PLC', 'Power Systems', 'Embedded Systems', 'C++', 'Signal Processing', 'PCB Design'],
  'civil':              ['AutoCAD', 'Revit', 'Structural Analysis', 'Project Management', 'Concrete Design', 'Geotechnical', 'CAD', 'BIM', 'Cost Estimation'],
  'chemical':           ['Process Design', 'MATLAB', 'Aspen Plus', 'Laboratory Skills', 'Safety Management', 'Chemical Analysis', 'Quality Control', 'R&D'],
  'biomedical':         ['MATLAB', 'Medical Device Knowledge', 'Laboratory Skills', 'Python', 'Biostatistics', 'Regulatory Affairs', 'Research', 'Clinical Trials'],
  'environmental':      ['Environmental Impact Assessment', 'GIS', 'AutoCAD', 'Data Analysis', 'Report Writing', 'Field Work', 'Sustainability', 'Compliance'],
  'nursing':            ['Patient Care', 'Clinical Assessment', 'Medical Records', 'Medication Administration', 'Teamwork', 'Communication', 'Emergency Response'],
  'medicine':           ['Clinical Skills', 'Patient Assessment', 'Medical Research', 'Diagnostic Skills', 'Communication', 'Teamwork', 'Evidence-Based Practice'],
  'psychology':         ['Counselling', 'Research Methods', 'SPSS', 'Assessment Tools', 'Report Writing', 'Active Listening', 'CBT', 'Case Management'],
  'biology':            ['Laboratory Skills', 'PCR', 'Cell Culture', 'Microscopy', 'Data Analysis', 'Research', 'Scientific Writing', 'Python', 'SPSS'],
  'chemistry':          ['Laboratory Skills', 'Analytical Chemistry', 'HPLC', 'GC-MS', 'NMR', 'Research', 'Data Analysis', 'Scientific Writing', 'Safety'],
  'pharmacy':           ['Pharmacology', 'Drug Dispensing', 'Patient Counselling', 'Medical Terminology', 'Regulatory Affairs', 'Research', 'Quality Assurance'],
  'public health':      ['Epidemiology', 'Health Promotion', 'Research Methods', 'SPSS', 'Policy Analysis', 'Data Analysis', 'Program Evaluation', 'Communication'],
  'nutrition':          ['Nutritional Assessment', 'Meal Planning', 'Research', 'Client Education', 'Food Science', 'Health Promotion', 'Data Analysis'],
  'education':          ['Curriculum Development', 'Classroom Management', 'Assessment', 'Communication', 'Lesson Planning', 'Learning Management Systems', 'Differentiated Instruction'],
  'teaching':           ['Lesson Planning', 'Curriculum Design', 'Classroom Management', 'Assessment', 'Student Engagement', 'Communication', 'Digital Literacy'],
  'law':                ['Legal Research', 'Contract Drafting', 'Negotiation', 'Legal Writing', 'Compliance', 'Case Management', 'Microsoft Word', 'Attention to Detail'],
  'legal':              ['Legal Research', 'Contract Review', 'Compliance', 'Legal Writing', 'Due Diligence', 'Negotiation', 'Corporate Law', 'Litigation Support'],
  'hospitality':        ['Customer Service', 'Event Management', 'Food & Beverage', 'Hotel Management', 'Reservations Systems', 'Communication', 'Teamwork', 'Revenue Management'],
  'tourism':            ['Customer Service', 'Travel Planning', 'GDS Systems', 'Communication', 'Cultural Awareness', 'Sales', 'Event Management', 'Marketing'],
  'human resources':    ['Recruitment', 'Onboarding', 'Performance Management', 'Employee Relations', 'HRIS', 'Payroll', 'Compliance', 'Training & Development', 'Communication'],
  'hr':                 ['Recruitment', 'Onboarding', 'Performance Management', 'Employee Relations', 'HRIS', 'Payroll', 'Compliance', 'Training & Development'],
  'general':            ['Communication', 'Problem Solving', 'Teamwork', 'Microsoft Office', 'Time Management', 'Critical Thinking', 'Leadership', 'Adaptability', 'Customer Service'],
};

export function getSuggestedSkills(major: string): string[] {
  if (!major.trim()) return MAJOR_SKILLS_MAP['general'];
  const lower = major.toLowerCase();
  for (const [keyword, skills] of Object.entries(MAJOR_SKILLS_MAP)) {
    if (lower.includes(keyword)) return skills;
  }
  return MAJOR_SKILLS_MAP['general'];
}
